---
- name: CFME | Install VDDK
  hosts: all
  gather_facts: True
  tasks:
    - name: CFME | Install VDDK | Extract VDDK
      unarchive:
        src: "{{ cfme_vddk_path }}"
        dest: /tmp/

    - name: CFME | Install VDDK | Sync Folder to /usr/lib
      synchronize:
        src: /tmp/vmware-vix-disklib-distrib
        dest: /usr/lib/vmware-vix-disklib

    - name: CFME | Install VDDK | Link libvixDiskLib.so
      file:
        src: /usr/lib/vmware-vix-disklib/lib64/libvixDiskLib.so
        dest: /usr/lib/libvixDiskLib.so
        state: link

    - name: CFME | Install VDDK | Link libvixDiskLib.so.6
      file:
        src: /usr/lib/vmware-vix-disklib/lib64/libvixDiskLib.so.6
        dest: /usr/lib/libvixDiskLib.so.6
        state: link

    - name: CFME | Install VDDK | Run ldconfig
      command: 'ldconfig'
