---
- name: CFME | Rolling Update | All Preparation
  hosts: cfme
  become: True
  gather_facts: True
  tasks:
    - name: CFME | Rolling Update | Include Tasks for Configuring Repositories
      include_tasks: tasks/configure-repositories.yml

    - name: CFME | Rolling Update | Any package updates required?
      command: 'yum check-update --releasever={{ ansible_release_version }}'
      args:
        warn: no
      register: packages_need_update_result
      changed_when: packages_need_update_result.rc == 100
      failed_when: packages_need_update_result.rc != 0 and packages_need_update_result.rc != 100

- name: CFME | Rolling Update | Update Databases
  hosts: cfme-databases
  become: True
  gather_facts: False
  serial: 1
  tasks:
    - name: CFME | Rolling Update | Include Tasks for Updating Packages
      include_tasks: tasks/update-packages.yml
      when: packages_need_update_result | changed

- name: CFME | Rolling Update | Update Appliances
  hosts: cfme-appliances:!cfme-databases
  become: True
  gather_facts: False
  serial: 1
  tasks:
    - name: CFME | Rolling Update | Include Tasks for Updating Packages
      include_tasks: tasks/update-packages.yml
      when: packages_need_update_result | changed
